- .gitignore
- mh/constants.py
- mh/pat.py
Gate & city chat implementation with option to change the colors of the text chat for each layer.
> Implemented Gate & City Chat

- fmp_server.py
- mh/pat.py
I did a bit of code deduplication.
I still need to test it before switching to a complete PR.
> PAT: Create a circle_broadcast helper

- fmp_server.py
> PAT: Fix docstring

- fmp_server.py
- mh/database.py
- mh/pat_item.py
- mh/session.py
This are all the changes that I have accumulated over time, about the circle functionality. I have tried to make every commit as atomic as possible, so you could review it commit by commit. 
I wanted to keep going and implement a few more thing, but I realized that we needed to change the `Players` collection object, and since it's not strictly related to circles I wanted to get this in first.
(If you need me to describe the PR a little bit more, ping me)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sepalani/mh3sp/35)
> Implement more circle related features

- mh/database.py
- mh/pat.py
- mh/pat_item.py
- mh/session.py
- other/utils.py
This PR implements the city search feature that can be used at the gate next to the arena search lady.
> PAT: Implement LayerDetailSearch packets

- mh/pat.py
- mh/pat_item.py
This PR adds PatData support to the Unpacker class. That way, the offset computations are done automatically by the unpacker on top of checking the packing/unpacking consistency.
> PAT: Add PatData support to the Unpacker class

- fmp_server.py
- mh/database.py
- mh/session.py
Fix player location in city's player list
In City|Quest
-|-
Fix player location when searching city
In City|Quest
-|-
> Fix player location in city's player list

- fmp_server.py
Like the title say, let's not assert on stuff that can be handled by the player.
> Remove asserts in favor of client messages

- mh/pat_item.py
- mh/session.py
Before (from the Test Server):
After:
> Properly send the weapon type in the CircleInfo

- fmp_server.py
- mh/constants.py
- mh/database.py
- mh/pat.py
- mh/session.py
… through means other than the city entrance
This does not include code for city owners to transfer ownership upon disconnection.
Edit: This now includes code for city owners to transfer ownership upon disconnection.
> Added code for disconnecting from layers

- mh/quest_utils.py
Added Phantom Uragaan & Blood Sport Description
Increased super alatreon's size based on info that super ala was bigger
> Fixed event quest descriptions & some monster sizes

- other/utils.py
This PR should fix issues related to SSL ciphers and OpenSSL issues which are dependent of the OS security policies and python's OpenSSL version. This PR is targeting the master branch.
> Hardcode Wii SSL ciphers

- fmp_server.py
- mh/database.py
- mh/pat.py
- mh/pat_item.py
- mh/session.py
- Filled in `unk` to send the correct value, the number of players signed up for the circle
- Made disconnecting from the server gracefully remove you from the circle list/delete the quest if you're the host
- Made emptying out a city now reset all corresponding circles, preventing persistent "ghost quests"
> Made quests(circles) more stable

- mh/pat.py
Fix to a reversion that removed the `LineCheck`-based client timeout.
> Reimplemented client timeout

- mh/pat.py
- Tells now work
- Tells now work from inside a quest to inside a city, and the other way around
- Circle Tells now work when signed up for a quest in the city
> Implemented quest to city chat, Tells, and Circle Tells

- mh/constants.py
Filled-in the "ANNOUNCE" section to present the user with a notice welcoming them to the MH3SP Beta Test. The announcement reads as follows:
```
---------- MH3SP ----------
Monster Hunter 3 (Tri) Server Project
Welcome to the MH3SP Beta Test! We ask that you
keep few things in mind while connected in order to
make the experience as fun as possible for everyone.
No abusing other players, no exploiting bugs, and
please report bugs that you find to the server
staff/dev team. We thank you for your patience as
we prepared this server to be fit for public use,
and ask your continued patience in the weeks to
come as you may encounter some bugs and errors
while playing. Please see the Public Test Server
Roadmap for a list of features we are working on.
Welcome to Loc Lac!
```
> Added Welcome Screen Notice Message

- fmp_server.py
- mh/database.py
- mh/pat.py
- Added parent `Lockable` class for future thread-safe classes
- `Players` class now inherits from `Lockable` class
- Added locking guards to `Players` class methods that alter the state of the object
- Added `Players` locking guards to `pat` handlers that request the state of a `Players` object over multiple steps
> Players class: added Lock and improved thread-safety of related code

- fmp_server.py
This PR fixes a docstring typo.
> PAT: Fix NtcCircleListLayerDelete docstring

- mh/constants.py
- mh/quest_utils.py
A re-do of the event quest system now that the bulk of the event quest reverse engineering is done. Turned quest storage into an easily indexable `dict` that could, in the future, be easily serialized and stored in a file.
- Added new system for quest data entry
- Refactored all activated event quests
- Cleaned up quest_utils.py
> Event Quest Refactor

- fmp_server.py
- mh/database.py
- mh/pat.py
- mh/pat_item.py
- mh/session.py
`Circle` class now inherits from the `Lockable` class.
Added locking (using `with` blocks) sections to improve thread safety.
> Circle class: added Lock and improved thread-safety of related code

- fmp_server.py
- mh/database.py
- mh/pat.py
- mh/session.py
Extension of the `Locking` class inheritance logic to the `City` class.
> Added locking mechanism to City class

- mh/database.py
This PR adds an hybrid database based on the temporary database and a sqlite database. It provides a way to preserve the saved data between shutdowns. Currently, it preserves the data used by the following DB interfaces: `use_user`, `accept_friend` and `delete_friend`.
This PR also provides a thread-safe wrapper to workaround the SQLite concurrency limitations. I also used `setdefault` in the `DebugDatabase` to only set the default value if it doesn't exist.
Some remarks regarding my current approach:
- _(the most important one)_ Only the connection should be behind this thread_local wrapper. Otherwise, the database class and its data will be duplicated which means that each thread will have its own independent database with its (inconsistent) data.
- The current approach using a …
> Database: Add TempSQLiteDatabase class

- master_server.py
- mh/server.py
Set threads name for easier debugging.
> Set threads name

- fmp_server.py
- mh/arena_utils.py
- mh/constants.py
- mh/equipment_utils.py
- mh/pat.py
- mh/quest_utils.py
- mh/session.py
- mh/time_utils.py
This PR fixes PEP8 coding style issues. The purpose of this PR is to allow, in the future, the use of github actions and/or other CI/CD tools to check the code/PRs for issues.
@kbarkevich @InusualZ 
If the online event/arena quests don't match the ones of the closed-beta, do you mind to diff the quests from there against the dev branch so I can update this PR accordingly.
> PEP8: Fix most issues from our files

- cert/MHTriCertPatcher.py
- fmp_server.py
- mh/pat.py
- mh/pat_item.py
- mh/server.py
- mh/session.py
- opn_server.py
This should be good enough before setting up GitHub actions.
> Ruff: Linting

- mh/constants.py
`Stream Lobby` - For when someone is streaming
`Turns` - Each player take a turn selecting the quest to do
> New seeking types suggested by the open beta players

- mh/pat.py
Log incoming connection IP and Capcom ID
> Add client identifiable logging messages

- fmp_server.py
- mh/database.py
- mh/pat.py
- mh/pat_item.py
- mh/session.py
Demo:
https://streamable.com/nbxtwl
> City List Live Update

- mh/server.py
A follow up of https://github.com/sepalani/MH3SP/pull/114.
This PR fixes deadlocks when exceptions occur early (ex: ports already used) since `__is_shut_down` wasn't set and `close` is waiting for the event.
I also changed `max_threads` _(which only auto-detect when set to zero, now, which is the default value)_ as we don't use negative numbers, AFAICT.
> Fix deadlocks when an error occurs early

- fmp_server.py
- mh/database.py
- mh/session.py
- other/utils.py
This PR fixes some of the python 3 issues.
> Fix python3 issues

- debug.ini
- master_server.py
- other/debug.py
- other/utils.py
This PR adds debug handlers for maintained modules with Python2/3 debugging capabilities. I tested most of them on Windows' python and cygwin's python. ~I still have to test some of them with my Linux machine and add another config file for more flexibility.~
> Add a debugging helper module

- mh/pat.py
- mh/server.py
- other/utils.py
Generic alternative to https://github.com/sepalani/MH3SP/pull/120.
> Workaround to prevent TLS handshakes to hang the server

- mh/constants.py
- res/trading_post.py
I added a resources folder to be used when dealing with resources that we will need to generate from python data and/or a file. I implemented all known trades for the trading post lady.
Implementing a rotation system isn't in the scope of this PR.
> Add all trades from the online trading post
