fmp_server.py
mh/pat.py
mh/pat_item.py
mh/session.py

Solution uses class `UserBinarySet` that is an extension of `PatData`. The `UserBinarySet` is unlike other instances of `PatData` since it is essentially one giant block of consistently-sized binary without the usual item types. It is also rarely sent in its entirely to the server, with an offset provided to show how deep into the binary the transmission actually begins.
An override `unpack()` class method was created using a hardcoded `LENGTHS` tuple to describe the size of each segment of the `UserBinarySet` data from beginning to end. When the server receives a chunk of this binary via `recvReqUserBinarySet`. it determines which values inside the `UserBinarySet` were actually obtained from the client and then updates only those.
When a player's `UserBinarySet` is to be distributed to …

Implemented weapon, hunter status/profile, armor, and HR transmission

---

fmp_server.py
mh/constants.py
mh/database.py
mh/pat.py
mh/pat_item.py
mh/session.py

This PR reverts some weird formatting changes like confusing newline, space removal between operators, etc. A rule of thumb would be not to lint code unrelated to a PR and avoid auto-linting the code. Using `pep8` and `pycodestyle` from time to time is more than enough. Unless the code is really dirty, it's rare to trigger the linter.
Ready to be reviewed & merged when tested.

Revert some formatting changes

---

mh/database.py
mh/pat.py
mh/pat_item.py
mh/session.py

This PR retains city's optional fields used to display the city properties at the gate.
I'll test it soon to make sure it doesn't break anything, meanwhile I'm setting it as a draft.

PAT: Use layer's optional fields

---

mh/database.py
mh/pat.py
mh/session.py

This PR prevents multiple users to use simultaneously the same Capcom ID. It also provides a wrapper that can forward tiny error messages to the game.

Fix CapcomID persistence across session

---

mh/database.py
mh/pat.py
mh/pat_item.py
mh/session.py
other/utils.py

This PR implements the packets used in the `Online > Player Search` menu. I also added an `Unpacker` helper class and fixed some stuff here and there.
What this PR doesn't do:
- Implement some of the already missing/dummy data fields (the city size/capacity)
- Implement/save the player location (in city/quest)
- Implement the warp system
- Implement the friendlist/friend packets
- (...)
This PR should be ready to be tested.

PAT: Implement player search packets

---

mh/database.py

This PR fixes an assertion error which spotted an issue in the Capcom ID creation. This assertion happens when you select an empty user slot.

Database: Fix Capcom ID creation

---

mh/pat_item.py

This PR fixes an unpacking implementation error. This was unnoticed since most of the time the game didn't expect meaningful data from it when used.

PAT: Fix unpack_detailed_optional_fields offset

---

fmp_server.py
mh/database.py
mh/pat.py
mh/pat_item.py

The game uses a collection of slot to store the players of the current layer. In some packets the server must send a valid player index and this index must reflect the position in the slot collection across all players in the same layer. With our previous collection (plain `list`) this wasn't possible because if at some point someone was removed from the collection, all other player index position would become invalid.
Now we implement that sort of collection with a list of slot (default `None`). When someone is added we give it the first empty (`None`) slot and when someone is removed we empty-out (set to `None`) the slot. With this any other player index position stay the same throughout their connection in the layer.

Replace `Players` collection

---

fmp_server.py
mh/database.py
mh/session.py

We needed to track the session (player) a little bit with more detail, so I came up with this idea. But to be honest, after implementing it, I'm not too exited about it. Maybe there is better/simpler way?
Anyway, this allow me to fix two things:
- Previously, if someone created a circle and someone joined the circle and set himself as ready (standby), but another player joined after him, that other player wouldn't be able to see him (when in-quest) because the second player was ready (standby) before the third joined the circle. In other words, we weren't communicating the players that were ready, before you joined.
- Previously, we were sending to the circle's quest, everyone who enlisted in the circle ignoring if they were ready (standby) or not.
fix #41

Track the session state

---

fmp_server.py
mh/pat.py

Previously, when leader of a circle (quest) set a password, we weren't verifying it when another player joined the circle.
Also, we now have a proper method of communicating with the client a non-fatal error message

Circle password

---

fmp_server.py
mh/database.py
mh/pat_item.py

We now have the capability to properly serialize our self the member of a circle. That way when we made changes to the collection of participant of a circle, we can send the changes without waiting for the circle's leader to acknowledge the changes himself.
For now, we only fix the case were if somebody is left behind (because he/she wasn't ready) when departing for a quest, we propagate the change correctly.
Other fixed would come after we properly detect and cleanup when somebody disconnect

Properly propagate changes in the circle's member collection

---

mh/pat.py

Previously weren't shutting down the `StreamRequestHandler` when sending `AnsShut`/`NtcShut`. This caused problems because when the handler was going to loop back and `::select` the socket, it was closed by the client (requested by us) causing the system to throw an exception that wouldn't be handled, This in-turn caused that the `session`'s resources weren't being saved/free properly.

Properly shutdown when requested

---

mh/pat.py

I was wrong, it still needed :(
Let's not have a broken `dev` branch.

Re-add timeout workaround

---

config.ini
other/utils.py

This PR fixes issues related to SSL security being too weak. It targets the master branch as some users are concerned especially when running the server on recent OS and Linux distributions. I chose to disable the option by default since I don't think it's a good idea to bypass existing security policies and people doing so should be aware of that.
Ready to reviewed & merged.

Add legacy SSL ciphers support

---

fmp_server.py
mh/pat.py

This PR fixes a bug when, in some circumstances like disconnection or race condition, the `pat_handler` is `None` and try to call the `send_packet` method.

PAT: Check that the handler (still) exists before a broadcast

---

mh/database.py
mh/pat.py
mh/session.py

Added code to prevent the creation of invalid cities.
This included cities that already exist, or are already reserved by another user in the city creation menu.
This would fix, among others, the bug pictured below.
This does NOT implement city list refreshing. It simply removes the more severe consequences of the city list not refreshing, such as server/client crashes and layer misplacement.

City creation and joining bug

---

.gitignore
mh/constants.py
mh/quest_utils.py
other/utils.py

Updated event quest generator to reflect new information
Added quest location enum and foundation for event quest generator functions
Added monster enum
Added quest rank type enum
added monster quest type maker
Added event quest boilerplate (can't launch)
Functional event quests
Added Sample Event Quests & Added Event Quest Analysis
Added egg transport event quest
Added dummy small monster support
Small monster data can be loaded from plaintext hex files
Added item drop table support
Added debug event quest
Added event quest "Jump Three Jaggi" (Jump Four Jaggi replacement)
Added event quest "Blood Sport"
Updated UNK labels and added "Mercy Mission" event quest
Added accurate World Eater quest
Updated documentation and quest details
Added The Phantom Uragaan
Added Where Gods Fear to Tread …

Added event quest support, 6 Tri event quests, and 1 custom event quest

---

other/utils.py

Not sure why enforcing TLSv1 work in some cases and don't in others for some people. Switching this PR as draft while I make sure it doesn't cause a regression from all my testing devices (i.e. Dolphin/real Wii and VPS/local server).

Allow all supported SSL protocols

---

mh/constants.py
mh/pat.py
mh/time_utils.py

Implemented serverside timers for day cycle ticks (counts backwards from epoch time) as well as server time (counts forwards from epoch time).
Also implemented cyclical Jhen Mohran event, which is based on server time and repeats every 14 days. This cycle starts with 1 day of fog followed by 2 days of sandstorm, and then 11 days of calm before repeating.

Added time passing and 14-day cycle for Jhen event

---

master_server.py
mh/pat.py
other/utils.py

- Added client timeout that disconnects a player and clears them from the server if they do not respond to a `LineCheck` packet in time
This has the effect of removing "stuck" players or "ghost" players who disconnected through strange means (such as internet going down) and would otherwise have their characters trapped in the server with their Capcom ID stuck in use.
- Added debug mode that disables the timeout
Since pausing Dolphin and looking through the active memory is such a huge part of this server's development, I implemented a "debug mode" that can be enabled through a launch argument `-d` or `--debug_mode` that disables the timeout and thus allows a developer to pause Dolphin for extended periods without getting disconnected.

Added client timeout & debug mode that disables it

---

mh/constants.py
mh/pat_item.py
mh/quest_utils.py

This PR addresses https://github.com/sepalani/MH3SP/issues/71. I'm going to insta-merge it since it prevents me for working on _(both python2 and)_ python3. I chose the use `encode("ascii")` as a quick workaround and also not to have a huge code diff converting all strings and operations on string to bytes.
@InusualZ I removed the `hunter_name` conversion _(from str to bytes)_ as it seems retrieved as bytes by the server _(I assume it's because it's sent by the game)_. Feel free to revert this change or use an alternative if it produces bugs elsewhere. It was preventing me from creating a quest.

Fix Python3 errors

---

mh/constants.py
mh/quest_utils.py
mh/time_utils.py

Greeter text changes based on sandstorm status. This can be further updated to support automatically-changing event quests (and arena quests) once that feature is implemented. In the meantime, since they are hardcoded, the event quest names in the Greeter menu are hardcoded (with the exception of the Jhen event quest, which only appears if there is a sandstorm)

Added dynamically updating greeter text

---

mh/pat.py
mh/server.py
mh/session.py

Re-implemented logic based on the byte sent with the `ReqShut` packet, which, if 1, instructs the server to disconnect the player completely. It differentiates between when the client is switching from one server to another, and when the client is fully disconnecting from the game.
This fixes the bug where, when players disconnected from the screen that displays the list of gates in a server, they would not be removed from the list of players in the server. This resulted in an incorrect player count in the affected server.

Fixed bug with incorrect player count in Servers

---

mh/constants.py
mh/time_utils.py

This PR fixes the issue where players who log in later than others have their times initialized ahead of everybody else.
This was caused due to the "countdown" that was previously used to advance time. With the addition of the time-based event quests, the correct timer now progresses forwards, making the countdown unneeded. The countdown has been replaced with a single variable set upon server initialization to the timestamp at which the server was booted up. As a consequence, the in-game day/night cycle will always start at the beginning of daytime when the server boots up.
If we wished to make the day/night cycle continuous even across periods when the server was off, like it was before, we could set the value to a constant timestamp instead.

Fixed time divergence issue

---

fmp_server.py
mh/pat.py
mh/pat_item.py

This PR fixes equipment not being updated for other players. It addresses one item of the roadmap (https://github.com/sepalani/MH3SP/issues/44). Note to self: packet state `66320200 (AnsUserBinaryNotice)` can be changed to `OK` (https://github.com/sepalani/MH3SP/issues/83) except for the Japanese version (which can't be tested, at the moment).
Ready to be reviewed, tested & merged.

PAT: Fix NtcUserBinaryNotice implementation

---

mh/pat.py
mh/pat_item.py

This PR implements the NtcLayerMediation packets properly. At the moment, I kept them disabled since the city doesn't retain the mediation list and it can produce oddities upon player disconnection or player entering the city.

PAT: Implement NtcLayerMediation packets

---

mh/database.py
mh/pat.py
mh/session.py

This PR implements properly packets related to messages and friend lists. AFAICT, a stable index doesn't seem necessary as the friend list isn't shared with other players nor is involved in some kind of negotiation like city's host, quest slots, etc.
Tested on Python2/3 and on both the Japanese and US version of the game.
Ready to be reviewed, tested & merged.

Add message and friend list support

---

mh/constants.py

This PR adds missing seekings and some video references.
I'm unsure for `# TODO: "Skilled players only" doesn't appear in Rookie type servers?` so I left a question mark since I have no proof but that'd make sense since they did the opposite for the Expert type servers.

mh.constants: Add missing seekings

---

.github/workflows/python-ci.yml

This PR adds bare-bones Python CI. It only performs linting and setup various python versions. We will be able to add proper unit testing when we're ready.

GitHub Actions: Add Python CI

---

mh/server.py

Currently on `dev` if we try to run the server with Python v3 without `LegacySSL=ON` we would hit hit this error:
Which would crash the main thread, the issue is that the Python VM would not terminate the process instead it would wait for all the threads to be _joined_. This is problematic because the worker threads are expecting work to be done because they are started in the constructor of the server class. This in turn make the process unkillable by means of CTRL+C
Now we defer starting the worker threads until we actually start serving the server.

Start server worker thread when expecting work not before

---

config.ini
other/utils.py

This PR removes the `LegacySSL` option and picks automatically the appropriate SSL config.

Remove LegacySSL option and automatically pick the appropriate config
